---
title: "All About Quarto"
date: "April 12, 2025"
date-modified: "last-modified"
format: html
editor: visual
---

This page provides links to useful resources related Quarto.

## Overview

-   [Getting Started](https://quarto.org/docs/get-started/)
-   [RStudio IDE](https://quarto.org/docs/tools/rstudio.html)
-   [Using R](https://quarto.org/docs/computations/r.html)
-   [HTML Basics](https://quarto.org/docs/output-formats/html-basics.html)

## Create websites and blogs

-   [Creating a Website](https://quarto.org/docs/websites/)
-   [Website Navigation](https://quarto.org/docs/websites/website-navigation.html)
-   [Document Listings](https://quarto.org/docs/websites/website-listings.html)

## Authoring Guide

-   [Markdown Basics](https://quarto.org/docs/authoring/markdown-basics.html)
-   [Figures](https://quarto.org/docs/authoring/figures.html)
-   [Tables](https://quarto.org/docs/authoring/tables.html)
-   [Diagrams](https://quarto.org/docs/authoring/diagrams.html)
-   [Citations & Footnotes](https://quarto.org/docs/authoring/footnotes-and-citations.html)
-   [Cross References](https://quarto.org/docs/authoring/cross-references.html)
-   [Article Layout](https://quarto.org/docs/authoring/article-layout.html)

## Useful web resources

-   [Awesome Quarto](https://github.com/mcanouil/awesome-quarto#featured-new-releases). This github repository provides a comprehensive listing of Quarto resources. It should be the second stop (after Quarto homepage) if you need to look for revelent materials about Quarto.

## Website prepared by seniors

### AY2023-24 January Term

-   [Imran’s Visual Analytics page](https://imranmi-isss608-jan24.netlify.app/)
-   [Victoria's Visual Analytics page](https://iss608-vaa-victorianeo.netlify.app/)
-   [Kale's Visual Analytics Tales](https://akalestale.netlify.app/)

### AY2023-24 April Term

-   [Alicia's VA Webpage](https://lnealicia-isss608.netlify.app/)
-   [Joshua's VA Journey](https://joshuaisaiah.netlify.app/)
