---
title: "TH_EX1"
date: "Feb 1, 2026"
date-modified: "last-modified"
format: html
execute: 
  freeze: true
editor: visual
---

::: callout-note
## Creating data visualisation that is enligthening and truthful

Creating enlightening and truthful data visualizations involves focusing on accuracy, transparency, and the ability to effectively communicate insights. It's about presenting data in a way that is both informative and aesthetically pleasing, ensuring the audience can grasp the information quickly and accurately.
:::

## Overview

This handout provides the context, task, expectations and grading criteria of Take-home Exercise 1. Students must review and understand them before getting started with the take-home exercise.

## Setting the scene

Survey analysis is the process of transforming raw survey data into decision-relevant insights.  It focuses on identifying patterns, trends, and relationships within responses by using descriptive methods (such as counts, percentages, and averages) as well as inferential methods (such as correlations and significance tests) to interpret results and inform decision-making.

## The Task

For this take-home exercise, students are required to select one of the survey datasets below and apply appropriate, visually-driven survey analysis methods to reveal and communicate **at least five** and **no more than ten** key observations derived from their analysis.

- [Income of informal labourers in rural areas: A survey dataset of northern mountainous regions in Vietnam](https://www.sciencedirect.com/science/article/pii/S235234092100576X)
- [Dataset of factors affecting learning outcomes of students at the University of Education,Vietnam National University, Hanoi](https://www.sciencedirect.com/science/article/pii/S2352340925001702)

## The Designing Tool

The data should be processed by using appropriate **tidyverse** family of packages and the data visualisation must be prepared using **ggplot2** and **its extensions**.

::: callout-important
No interactive data visualisation are required.
:::

## The Write-up

The write-up of the take-home exercise should include but not limited to the followings:

-   A reproducible description of the procedures used to prepare the analytical visualisation. Please refer to the senior submission I shared below.

-   A write-up of no more than **150 words** per each data visualisation, describing and discussing the patterns reveal by each visualisation prepared.

# Submission Instructions

This is an individual assignment. You are required to work on the take-home exercises and prepare submission individually.

::: callout-important
The specific submission instructions are as follows:

-   The analytical visualisation must be prepared by using **R and appropriate R packages**.
-   The write-up of the take-home exercise must be in **Quarto html document** format. You are required to publish the write-up on [**Netlify**](https://www.netlify.com/).
:::

## Submission date

The completed take-home exercise is due on **15th February 2026 (Sunday) by 11:59pm mid-night**.

## Learning from senior

-   [KYLIE TAN JING YI](https://akalestale.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [TOA ZI YING JANET](https://janettoaisss608.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LEW YING ZHEN SERENA](https://isss608-spacebun.netlify.app/take-home_ex/take-home_ex1/take-home_ex1)
-   [SENG JING YI](https://jingyi-vaa.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [JAYA GEORGE](https://isss608-jayageorge.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)

## Peer Learning